
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 24 04:41:16 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 35;
  public static final int LTE = 29;
  public static final int LBRACKET = 21;
  public static final int INCREMENT = 10;
  public static final int CONST = 5;
  public static final int NUMCONST = 12;
  public static final int NOTEQUAL = 25;
  public static final int CONTINUE = 41;
  public static final int LPAREN = 16;
  public static final int MINUS = 33;
  public static final int DECREMENT = 11;
  public static final int RPAREN = 17;
  public static final int SEMICOLON = 7;
  public static final int AND = 30;
  public static final int LT = 28;
  public static final int OR = 31;
  public static final int COMMA = 18;
  public static final int CLASS = 45;
  public static final int PLUS = 32;
  public static final int MULTIPLY = 34;
  public static final int IF = 37;
  public static final int THIS = 46;
  public static final int DOT = 20;
  public static final int EOF = 0;
  public static final int RETURN = 42;
  public static final int RBRACKET = 22;
  public static final int EQUAL = 23;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int ISEQUAL = 24;
  public static final int BREAK = 40;
  public static final int IDENT = 19;
  public static final int VOID = 6;
  public static final int GTE = 27;
  public static final int ARROW = 44;
  public static final int COLON = 47;
  public static final int FOREACH = 43;
  public static final int ELSE = 38;
  public static final int LBRACE = 3;
  public static final int ENUM = 50;
  public static final int READ = 8;
  public static final int WHILE = 39;
  public static final int CHARCONST = 13;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 49;
  public static final int BOOLCONST = 14;
  public static final int PROG = 2;
  public static final int MODUO = 36;
  public static final int GT = 26;
  public static final int DO = 48;
  public static final int PRINT = 9;
}

