
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Dec 19 03:34:40 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int READ = 8;
  public static final int MULTIPLY = 26;
  public static final int IDENT = 19;
  public static final int SEMICOLON = 7;
  public static final int PLUS = 24;
  public static final int MODUO = 28;
  public static final int RPAREN = 17;
  public static final int RBRACE = 4;
  public static final int EQUAL = 23;
  public static final int DECREMENT = 11;
  public static final int LBRACKET = 21;
  public static final int LPAREN = 16;
  public static final int LBRACE = 3;
  public static final int RBRACKET = 22;
  public static final int NUMCONST = 12;
  public static final int COMMA = 18;
  public static final int EOF = 0;
  public static final int DIVIDE = 27;
  public static final int CHARCONST = 13;
  public static final int PROG = 2;
  public static final int INCREMENT = 10;
  public static final int MINUS = 25;
  public static final int DOT = 20;
  public static final int CONST = 5;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int NEW = 15;
  public static final int VOID = 6;
  public static final int BOOLCONST = 14;
}

