
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 28 03:56:18 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 31;
  public static final int LTE = 25;
  public static final int LBRACKET = 17;
  public static final int INCREMENT = 10;
  public static final int CONST = 5;
  public static final int NUMCONST = 49;
  public static final int NOTEQUAL = 21;
  public static final int CONTINUE = 37;
  public static final int LPAREN = 13;
  public static final int MINUS = 29;
  public static final int DECREMENT = 11;
  public static final int RPAREN = 14;
  public static final int SEMICOLON = 7;
  public static final int AND = 26;
  public static final int LT = 24;
  public static final int OR = 27;
  public static final int COMMA = 15;
  public static final int CLASS = 41;
  public static final int PLUS = 28;
  public static final int MULTIPLY = 30;
  public static final int IF = 33;
  public static final int THIS = 42;
  public static final int DOT = 16;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int RBRACKET = 18;
  public static final int EQUAL = 19;
  public static final int NEW = 12;
  public static final int error = 1;
  public static final int ISEQUAL = 20;
  public static final int IDENT = 47;
  public static final int BREAK = 36;
  public static final int VOID = 6;
  public static final int GTE = 23;
  public static final int ARROW = 40;
  public static final int COLON = 43;
  public static final int FOREACH = 39;
  public static final int LBRACE = 3;
  public static final int ELSE = 34;
  public static final int ENUM = 46;
  public static final int READ = 8;
  public static final int CHARCONST = 48;
  public static final int WHILE = 35;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 50;
  public static final int EXTENDS = 45;
  public static final int PROG = 2;
  public static final int MODUO = 32;
  public static final int GT = 22;
  public static final int DO = 44;
  public static final int PRINT = 9;
}

